### ISSUE TITLE
Unable to use Conda with covalent-ssh-plugin

### ISSUE THREAD

**Issue by poojithurao** [AgnostiqHQ/covalent-ssh-plugin#21]
### Environment

- **Covalent version**: 0.110.2
- **Covalent-SSH plugin version**: 0.3.0
- **Python version**: 3.8
- **Operating system**: Ubuntu 18.04.6 LTS

### What is happening?

While using the covalent-ssh-plugin for using other machines as worker nodes, the covalent does not run the code in the environment mentioned by the 'conda_env' variable. Rather, it executes all the code outside the conda environment.

This becomes inconvenient as most of the libraries available with ec2 instances come loaded as conda environments and installing them manually is cumbersome. 

### How can we reproduce the issue?

Using the ssh-plugin executor always runs the code outside conda environment.

### What should happen?

The code must be executed inside the mentioned conda environment.

**Comment by AlejandroEsquivel** [comment]
Closed by https://github.com/AgnostiqHQ/covalent-ssh-plugin/pull/28
