### ISSUE TITLE
`conda activate` fails to activate conda environments 

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent-ssh-plugin#33]
### Environment

- **Covalent version**: 0.177.0
- **Covalent-SSH plugin version**:0.8.0
- **Python version**: 3.8.13
- **Operating system**: Ubuntu 20.04

### What is happening?

Depending on how a VM is provisioned the SSH executor sometimes fails to run `conda activate [ENV NAME]` with error:
```CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

```

### How can we reproduce the issue?

By using the EC2 executor and executing a workflow it complains about being unable to activate the conda environment `covalent`

### What should happen?

The workflow should execute successfully.

**Comment by kessler-frost** [comment]
Closed by #34.
